BillingProcessor: prevent null pointer exception at handleActivityResult
  * passed in data may be null and will crash when checking extras

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=null} to activity
....
Caused by: java.lang.NullPointerException
at com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult(BillingProcessor.java:297)

Change-Id: Idbd1eaed2c2c97d7aee710f16056221461616b22